[package]
name = "concorde"
description = "reconfigurable lattice agreement"
version = "0.3.0"
authors = ["Graydon Hoare <graydon@pobox.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
keywords = ["lattice", "consensus", "agreement", "crdt"]
repository = "http://github.com/graydon/concorde"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pergola = "0.5.0"
itertools = "0.9.0"
log = "0.4"


[dev-dependencies]
futures = "0.3.4"
pretty_env_logger = "0.4"
stateright = "0.5.0"
