[package]
name = "concorde"
description = "reconfigurable lattice agreement"
version = "0.1.0"
authors = ["Graydon Hoare <graydon@pobox.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
keywords = ["lattice", "consensus", "agreement", "crdt"]
repository = "http://github.com/graydon/concorde"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.5.0", features = ["unstable"] }
pergola = "0.5.0"
itertools = "0.9.0"

[dev-dependencies]
futures = "0.3.4"
